exasol/release-droid

- .classpath
- .project
- .settings/org.eclipse.jdt.core.prefs
- .settings/org.eclipse.m2e.core.prefs
- doc/changes/changelog.md
- doc/oft-spec.css
- doc/system_requirements.md
- pom.xml
> 1: Create user-level requirements

- README.md
- doc/changes/changes_0.1.0.md
- src/main/java/com/exasol/Goal.java
- src/main/java/com/exasol/ReleaseRobot.java
- src/main/java/com/exasol/Runner.java
- src/main/java/com/exasol/github/GitHubPlatform.java
- src/main/java/com/exasol/release/ReleaseMakerFactory.java
- src/main/java/com/exasol/repository/AbstractGitHubGitBranchContent.java
- src/main/java/com/exasol/repository/GitHubGitRepository.java
- src/main/java/com/exasol/repository/JavaMavenGitBranchContent.java
- src/main/java/com/exasol/validation/GitHubPlatformValidator.java
- src/main/java/com/exasol/validation/GitRepositoryValidator.java
- src/main/java/com/exasol/validation/PlatformValidatorFactory.java
- src/test/java/com/exasol/validation/GitHubPlatformValidatorTest.java
- src/test/java/com/exasol/validation/GitRepositoryValidatorTest.java
> #21: improved errors handling according to our new standards

- doc/changes/changes_0.1.0.md
- src/main/java/com/exasol/repository/AbstractGitHubGitBranchContent.java
- src/test/java/com/exasol/github/AbstractGitHubGitBranchContentTest.java
- src/test/java/com/exasol/repository/GitHubGitRepositoryTest.java
- src/test/java/com/exasol/repository/maven/JavaMavenGitBranchContentTest.java
> #27: Removed a deprecated method getContent

- .github/workflows/github_release.yml
- .github/workflows/maven.yml
- doc/changes/changes_0.1.0.md
- doc/design.md
- doc/user_guide/github_release_template.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/github/GitHubPlatform.java
> #33: Renamed 'Upload_release_assets.yml' to 'github_release.yml'

- src/main/java/com/exasol/repository/maven/MavenPomParser.java
rename throwParsingException to createParsingException
> fix #37  refactor MavenPomParser

- doc/changes/changes_0.2.0.md
- doc/design.md
- doc/system_requirements.md
- pom.xml
- src/main/java/com/exasol/CredentialsProvider.java
- src/main/java/com/exasol/ReleaseRobot.java
- src/main/java/com/exasol/ReportWriter.java
- src/main/java/com/exasol/RepositoryHandler.java
- src/main/java/com/exasol/Runner.java
- src/main/java/com/exasol/UserInput.java
- src/main/java/com/exasol/repository/AbstractGitHubGitBranchContent.java
- src/main/java/com/exasol/repository/GitRepositoryException.java
- src/main/java/com/exasol/repository/maven/MavenPomParser.java
- src/main/java/com/exasol/validation/GitHubPlatformValidator.java
- src/main/java/com/exasol/validation/GitRepositoryValidator.java
- src/main/java/com/exasol/validation/PlatformValidatorFactory.java
- src/main/java/com/exasol/validation/ValidationReport.java
- src/main/java/com/exasol/validation/ValidationResult.java
- src/test/java/com/exasol/RepositoryHandlerTest.java
- src/test/java/com/exasol/UserInputTest.java
- src/test/java/com/exasol/github/AbstractGitHubGitBranchContentTest.java
- src/test/java/com/exasol/repository/maven/JavaMavenGitBranchContentTest.java
- src/test/java/com/exasol/validation/GitHubPlatformValidatorTest.java
- src/test/java/com/exasol/validation/GitRepositoryValidatorTest.java
- src/test/java/com/exasol/validation/PlatformValidatorFactoryTest.java
- src/test/java/com/exasol/validation/ValidationReportTest.java
> * #25: Added a validation report.

- .github/workflows/dependencies_check.yml
- .github/workflows/maven_central_release.yml
- doc/changes/changes_0.2.0.md
- src/main/java/com/exasol/releaserobot/AbstractPlatform.java
- src/main/java/com/exasol/releaserobot/MavenPlatform.java
- src/main/java/com/exasol/releaserobot/Platform.java
- src/main/java/com/exasol/releaserobot/ReleaseRobot.java
- src/main/java/com/exasol/releaserobot/github/GitHubEntityFactory.java
- src/main/java/com/exasol/releaserobot/github/GitHubPlatform.java
- src/main/java/com/exasol/releaserobot/release/GitHubReleaseMaker.java
- src/main/java/com/exasol/releaserobot/release/MavenReleaseMaker.java
- src/main/java/com/exasol/releaserobot/release/ReleaseMakerFactory.java
- src/main/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContent.java
- src/main/java/com/exasol/releaserobot/validation/AbstractPlatformValidator.java
- src/main/java/com/exasol/releaserobot/validation/GitHubPlatformValidator.java
- src/main/java/com/exasol/releaserobot/validation/MavenPlatformValidator.java
- src/main/java/com/exasol/releaserobot/validation/PlatformValidatorFactory.java
- src/test/java/com/exasol/releaserobot/AbstractPlatformTest.java
- src/test/java/com/exasol/releaserobot/PlatformNameTest.java
- src/test/java/com/exasol/releaserobot/github/GitHubPlatformTest.java
- src/test/java/com/exasol/releaserobot/release/GitHubReleaseMakerTest.java
- src/test/java/com/exasol/releaserobot/release/MavenReleaseMakerTest.java
- src/test/java/com/exasol/releaserobot/release/ReleaseMakerFactoryTest.java
- src/test/java/com/exasol/releaserobot/validation/GitHubPlatformValidatorTest.java
- src/test/java/com/exasol/releaserobot/validation/PlatformValidatorFactoryTest.java
> #36: Added Maven release support.

- doc/changes/changes_0.2.0.md
- pom.xml
- src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
- src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
- src/main/java/com/exasol/releaserobot/main/Runner.java
- src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
- src/main/java/com/exasol/releaserobot/maven/MavenRepositoryValidator.java
- src/main/java/com/exasol/releaserobot/repository/AbstractGitHubGitBranchContent.java
- src/main/java/com/exasol/releaserobot/repository/GitRepository.java
- src/main/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContent.java
- src/main/java/com/exasol/releaserobot/repository/maven/MavenPlugin.java
- src/main/java/com/exasol/releaserobot/repository/maven/MavenPom.java
- src/main/java/com/exasol/releaserobot/repository/maven/MavenPomParser.java
- src/main/java/com/exasol/releaserobot/usecases/ReportImpl.java
- src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
- src/main/java/com/exasol/releaserobot/usecases/validate/AbstractPlatformValidator.java
- src/main/java/com/exasol/releaserobot/usecases/validate/BasicMavenPomValidator.java
- src/main/java/com/exasol/releaserobot/usecases/validate/GitRepositoryValidator.java
- src/main/java/com/exasol/releaserobot/usecases/validate/RepositoryValidator.java
- src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
- src/test/java/com/exasol/releaserobot/maven/MavenRepositoryValidatorTest.java
- src/test/java/com/exasol/releaserobot/report/ReleaseReportTest.java
- src/test/java/com/exasol/releaserobot/report/ReportWriterTest.java
- src/test/java/com/exasol/releaserobot/repository/maven/JavaMavenGitBranchContentTest.java
- src/test/java/com/exasol/releaserobot/repository/maven/MavenPomParserTest.java
- src/test/java/com/exasol/releaserobot/usecases/validate/BasicMavenPomValidatorTest.java
> * #46: Separated pom parsing and validation.

- doc/changes/changes_0.2.0.md
- src/main/java/com/exasol/releaserobot/github/GithubRepositoryGateway.java
- src/main/java/com/exasol/releaserobot/main/Runner.java
- src/main/java/com/exasol/releaserobot/main/UserInputParser.java
- src/main/java/com/exasol/releaserobot/report/ReportWriter.java
- src/main/java/com/exasol/releaserobot/usecases/UserInput.java
- src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
- src/test/java/com/exasol/releaserobot/main/UserInputParserTest.java
- src/test/java/com/exasol/releaserobot/report/ReportWriterTest.java
- src/test/java/com/exasol/releaserobot/usecases/UserInputTest.java
> * #68: Extracted UserInput parsing.

- doc/changes/changes_0.2.0.md
- doc/design.md
- doc/system_requirements.md
- pom.xml
- src/main/java/com/exasol/releaserobot/github/GitHubPlatformValidator.java
- src/main/java/com/exasol/releaserobot/github/GitHubReleaseMaker.java
- src/main/java/com/exasol/releaserobot/main/ReleaseRobot.java
- src/main/java/com/exasol/releaserobot/maven/MavenPlatformValidator.java
- src/main/java/com/exasol/releaserobot/maven/MavenReleaseMaker.java
- src/main/java/com/exasol/releaserobot/repository/maven/MavenRepository.java
- src/main/java/com/exasol/releaserobot/usecases/Repository.java
- src/main/java/com/exasol/releaserobot/usecases/release/ReleaseInteractor.java
- src/main/java/com/exasol/releaserobot/usecases/validate/ValidateInteractor.java
- src/main/java/com/exasol/releaserobot/usecases/validate/ValidateUseCase.java
- src/test/java/com/exasol/releaserobot/github/AbstractRepositoryTest.java
- src/test/java/com/exasol/releaserobot/github/GitHubPlatformValidatorTest.java
- src/test/java/com/exasol/releaserobot/maven/MavenPlatformValidatorTest.java
- src/test/java/com/exasol/releaserobot/maven/MavenReleaseMakerTest.java
- src/test/java/com/exasol/releaserobot/repository/maven/MavenRepositoryTest.java
> #81: Fixed requirements tracing.

- doc/changes/changes_0.2.1.md
- doc/user_guide/changes_file_template.md
> #90: Improved the changes file template.

- doc/changes/changes_0.2.1.md
- src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java
- src/test/java/com/exasol/releasedroid/repository/ReleaseLetterParserTest.java
> #89: Fix false positive validation for open ticket

- doc/changes/changes_0.3.0.md
- src/main/java/com/exasol/releasedroid/usecases/PlatformName.java
- src/main/java/com/exasol/releasedroid/usecases/UserInput.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
- src/main/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidator.java
- src/main/java/com/exasol/releasedroid/usecases/validate/ValidateInteractor.java
- src/test/java/com/exasol/releasedroid/usecases/PlatformNameTest.java
- src/test/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidatorTest.java
> * #100: Added release priority: 1. MAVEN, 2.GITHUB.

- doc/changes/changes_0.3.0.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/releasedroid/main/UserInputParser.java
- src/test/java/com/exasol/releasedroid/main/UserInputParserTest.java
> * #92: Allow input multiple platforms separately: `-p github -p maven`.

- doc/changes/changes_0.3.0.md
- doc/design.md
- doc/system_requirements.md
- pom.xml
- src/main/java/com/exasol/releasedroid/github/GitHubRepositoryModifier.java
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/repository/ReleaseLetter.java
- src/main/java/com/exasol/releasedroid/repository/ReleaseLetterParser.java
- src/main/java/com/exasol/releasedroid/repository/RepositoryModifier.java
- src/main/java/com/exasol/releasedroid/repository/maven/MavenRepository.java
- src/main/java/com/exasol/releasedroid/usecases/BaseRepository.java
- src/main/java/com/exasol/releasedroid/usecases/Repository.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
- src/main/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidator.java
- src/main/java/com/exasol/releasedroid/usecases/validate/ValidateInteractor.java
- src/test/java/com/exasol/releasedroid/github/BaseRepositoryTest.java
- src/test/java/com/exasol/releasedroid/github/GitHubRepositoryModifierTest.java
- src/test/java/com/exasol/releasedroid/repository/ReleaseLetterParserTest.java
- src/test/java/com/exasol/releasedroid/usecases/validate/GitRepositoryValidatorTest.java
> * #107: Modify the release date if it's outdated.

- doc/changes/changelog.md
- doc/changes/changes_0.3.1.md
- pom.xml
- src/main/java/com/exasol/releasedroid/github/GitHubPlatformValidator.java
- src/test/java/com/exasol/releasedroid/github/GitHubPlatformValidatorTest.java
> * #114: Fixed validation of a code name for the GitHub release.

- doc/changes/changes_0.4.0.md
- src/main/java/com/exasol/releasedroid/repository/LocalRepositoryGate.java
> bug/124: Fixed a wrong error message

- doc/changes/changes_0.4.0.md
- src/main/java/com/exasol/releasedroid/maven/MavenPluginValidator.java
- src/main/java/com/exasol/releasedroid/repository/MavenPlugin.java
- src/main/java/com/exasol/releasedroid/repository/MavenPomParser.java
- src/test/java/com/exasol/releasedroid/maven/MavenPlatformValidatorTest.java
- src/test/java/com/exasol/releasedroid/repository/MavenPomParserTest.java
> * #134: Fixed parsing of the plugins in the pom file.

- doc/changes/changes_0.4.0.md
- doc/design.md
- src/main/java/com/exasol/releasedroid/maven/JavaRepositoryValidator.java
- src/main/java/com/exasol/releasedroid/maven/MavenPlatformValidator.java
- src/main/java/com/exasol/releasedroid/maven/MavenReleaseMaker.java
- src/test/java/com/exasol/releasedroid/maven/JavaRepositoryValidatorTest.java
- src/test/java/com/exasol/releasedroid/maven/MavenPlatformValidatorTest.java
- src/test/java/com/exasol/releasedroid/maven/MavenReleaseMakerTest.java
> * #136: Excluded `project-keeper-maven-plugin` from the version validation

- doc/changes/changes_0.5.0.md
- doc/user_guide/templates/maven_central_release_pom_file_template.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/releasedroid/adapter/java/JavaRepositoryValidator.java
- src/test/java/com/exasol/releasedroid/adapter/java/JavaRepositoryValidatorTest.java
> * #131: Refactored pom.xml plugins validations.

- doc/changes/changes_0.5.0.md
- doc/user_guide/templates/changes_file_template.md
- doc/user_guide/user_guide.md
> * #126: Updated changes file template.

- doc/changes/changes_0.5.0.md
- src/main/java/com/exasol/releasedroid/adapter/communityportal/CommunityPortalAPIAdapter.java
- src/main/java/com/exasol/releasedroid/adapter/communityportal/CommunityPortalGateway.java
- src/main/java/com/exasol/releasedroid/adapter/communityportal/CommunityPortalReleaseMaker.java
> * #151: Added log output for created community post URL.

- doc/changes/changelog.md
- doc/changes/changes_0.6.0.md
- errorCodeConfig.yml
- pom.xml
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/usecases/ReleaseDroidConstants.java
- src/main/java/com/exasol/releasedroid/usecases/exception/ReleaseException.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseState.java
- src/main/java/com/exasol/releasedroid/usecases/request/PlatformName.java
- src/test/java/com/exasol/releasedroid/usecases/release/ReleaseStateTest.java
> * #159: Saved the release state.

- doc/changes/changes_0.6.0.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/releasedroid/main/ReleaseDroid.java
- src/main/java/com/exasol/releasedroid/usecases/request/UserInput.java
- src/test/java/com/exasol/releasedroid/main/ReleaseDroidTest.java
> * #161: Made VALIDATE a default goal.

- doc/changes/changes_0.6.0.md
- src/main/java/com/exasol/releasedroid/adapter/maven/MavenPlatformValidator.java
- src/main/java/com/exasol/releasedroid/adapter/maven/MavenPom.java
- src/main/java/com/exasol/releasedroid/adapter/maven/MavenPomParser.java
- src/test/java/com/exasol/releasedroid/adapter/maven/MavenPlatformValidatorTest.java
> * #164: Added additional validations for Maven platform.

- doc/changes/changes_0.6.0.md
- src/main/java/com/exasol/releasedroid/adapter/communityportal/CommunityPortalAPIAdapter.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubConnectorImpl.java
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraAPIAdapter.java
- src/main/java/com/exasol/releasedroid/usecases/PropertyReader.java
- src/main/java/com/exasol/releasedroid/usecases/PropertyReaderImpl.java
> * #174: Hid password on console.

- doc/changes/changes_0.6.0.md
- src/main/java/com/exasol/releasedroid/usecases/PropertyReaderImpl.java
> * #176: Fixed console input.

- doc/changes/changes_0.6.0.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubReleaseMaker.java
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraPlatformValidator.java
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java
- src/main/java/com/exasol/releasedroid/main/ReleaseDroid.java
- src/test/java/com/exasol/releasedroid/adapter/jira/JiraPlatformValidatorTest.java
> * #178: Deprecated and switched off community release.

- doc/changes/changelog.md
- doc/changes/changes_0.6.0.md
- doc/changes/changes_0.7.0.md
- doc/design.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubAPIAdapter.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubConstants.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubPlatformValidator.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubRelease.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubReleaseMaker.java
- src/test/java/com/exasol/releasedroid/adapter/github/GitHubPlatformValidatorTest.java
> * #173: Change GitHub uploading assets to an optional step.

- doc/changes/changes_0.7.0.md
- src/main/java/com/exasol/releasedroid/adapter/ReleaseManagerImpl.java
- src/main/java/com/exasol/releasedroid/adapter/RepositoryValidatorHelper.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubAPIAdapter.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubGateway.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubPlatformValidator.java
- src/main/java/com/exasol/releasedroid/adapter/github/GitHubRepositoryGate.java
- src/main/java/com/exasol/releasedroid/adapter/repository/CommonRepositoryValidator.java
- src/main/java/com/exasol/releasedroid/adapter/repository/LocalRepositoryGate.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseManager.java
- src/main/java/com/exasol/releasedroid/usecases/repository/BaseRepository.java
- src/main/java/com/exasol/releasedroid/usecases/repository/RepositoryGate.java
- src/test/java/com/exasol/releasedroid/adapter/github/GitHubAPIAdapterTest.java
- src/test/java/com/exasol/releasedroid/adapter/github/GitHubPlatformValidatorTest.java
- src/test/java/com/exasol/releasedroid/adapter/maven/MavenPlatformValidatorTest.java
- src/test/java/com/exasol/releasedroid/adapter/repository/CommonRepositoryValidatorTest.java
> * #182: Allowed release without checksum generation workflows

- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_0.7.0.md
- pom.xml
> * #30: Adjusted `release_droid_upload_github_release_assets.yml` tem[late to release with sha256sum.

- doc/changes/changes_0.7.0.md
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java
- src/test/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMakerTest.java
> * #185: Changed Jira tickets project to EXACOMM.

- doc/changes/changes_0.7.0.md
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraConfigParser.java
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java
- src/test/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMakerTest.java
> * #187: Allow configuring Jira project name via config file.

- doc/changes/changelog.md
- doc/changes/changes_0.7.1.md
- pom.xml
- src/main/java/com/exasol/releasedroid/adapter/ReleaseManagerImpl.java
- src/main/java/com/exasol/releasedroid/adapter/repository/CommonRepositoryValidator.java
- src/main/java/com/exasol/releasedroid/formatting/LogFormatter.java
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/main/UserInputParser.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseState.java
- src/main/java/com/exasol/releasedroid/usecases/repository/BaseRepository.java
> * #189: Fixed code smells.

- doc/changes/changes_0.7.1.md
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraReleaseMaker.java
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
> * #192: Made the config file optional for Jira release.

- doc/changes/changes_0.7.1.md
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/output/ResponseDiskWriter.java
- src/test/java/com/exasol/releasedroid/output/ResponseDiskWriterTest.java
> * #194: Create a report directory if missing.

- doc/changes/changelog.md
- doc/changes/changes_0.8.0.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/releasedroid/usecases/ReleaseDroidConstants.java
- src/test/java/com/exasol/releasedroid/adapter/repository/CommonRepositoryValidatorTest.java
> * #202: Allowed `v` in version's format.

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_0.8.1.md
- pom.xml
- src/main/java/com/exasol/releasedroid/usecases/PropertyReaderImpl.java
- src/test/java/com/exasol/releasedroid/usecases/PropertyReaderImplTest.java
> * #201: Added validation for credentials from a file.

- doc/user_guide/user_guide.md
> #214 Add some information on how to use release droid on windows

- doc/changes/changes_1.0.0.md
- pom.xml
> #223: Removed Spring Bean dependency with CVE-2022-22965

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_check.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- .github/workflows/release_droid_print_quick_checksum.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changes_1.0.0.md
- error_code_config.yml
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/releasedroid/main/RunnerIT.java
> #222: Add manifest with main-class

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_check.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- .github/workflows/release_droid_print_quick_checksum.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changes_1.0.0.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/releasedroid/adapter/jira/JiraAPIAdapter.java
- src/test/java/com/exasol/releasedroid/adapter/jira/JiraAPIAdapterTest.java
> #226: Fix Jira release

- .gitignore
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_1.1.0.md
- doc/design.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- error_code_config.yml
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/releasedroid/adapter/repository/JavaRepositoryValidator.java
- src/main/java/com/exasol/releasedroid/adapter/repository/RepositoryFactory.java
- src/main/java/com/exasol/releasedroid/main/ReleaseDroid.java
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/usecases/repository/ReleaseConfig.java
- src/main/java/com/exasol/releasedroid/usecases/repository/ReleaseConfigParser.java
- src/test/java/com/exasol/releasedroid/adapter/maven/MavenReleaseMakerTest.java
- src/test/java/com/exasol/releasedroid/adapter/repository/JavaRepositoryValidatorTest.java
- src/test/java/com/exasol/releasedroid/adapter/repository/RepositoryFactoryTest.java
- src/test/java/com/exasol/releasedroid/main/RunnerIT.java
- src/test/java/com/exasol/releasedroid/main/RunnerTest.java
- src/test/java/com/exasol/releasedroid/usecases/repository/ReleaseConfigParserTest.java
- src/test/java/com/exasol/releasedroid/usecases/repository/ReleaseConfigTest.java
fixes #228 multi module maven 
fixes #230 user_guide: command line parameters 
fixes #238 warn on missing file credentials
fixes #231 configure project language in file `release_config.yml`
> #228 Implemented

- doc/changes/changelog.md
- doc/changes/changes_1.3.1.md
- doc/user_guide/user_guide.md
- error_code_config.yml
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/releasedroid/adapter/repository/RepositoryFactory.java
- src/main/java/com/exasol/releasedroid/formatting/Colorizer.java
> #264 implemented

- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_1.3.2.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
> #267: Fixed vulnerabilities in dependencies.

- .gitattributes
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_1.3.2.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/releasedroid/usecases/repository/ReleaseConfigParser.java
- src/main/java/com/exasol/releasedroid/usecases/request/ReleasePlatforms.java
- src/test/java/com/exasol/releasedroid/main/ReleaseDroidTest.java
> #266: Improved warning message for unspecified release platforms.

- doc/changes/changelog.md
- doc/changes/changes_1.4.1.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
> #282: Excluded vulnerabilities

- .gitattributes
- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_1.5.0.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/releasedroid/output/guide/ShortTag.java
- src/test/java/com/exasol/releasedroid/Lines.java
- src/test/java/com/exasol/releasedroid/output/guide/ReleaseGuideTest.java
- src/test/java/com/exasol/releasedroid/output/guide/ShortTagTest.java
> Implemented #281

- doc/changes/changes_1.5.0.md
- doc/design.md
- src/main/java/com/exasol/releasedroid/main/ReleaseDroid.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
> Implemented #240

- dependencies.md
- doc/changes/changes_1.5.1.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/releasedroid/formatting/ReportLogFormatter.java
- src/main/java/com/exasol/releasedroid/main/ReleaseDroid.java
- src/main/java/com/exasol/releasedroid/main/Runner.java
- src/main/java/com/exasol/releasedroid/usecases/release/ReleaseInteractor.java
- src/test/java/com/exasol/releasedroid/formatting/ReportLogFormatterTest.java
- src/test/java/com/exasol/releasedroid/main/ReleaseDroidTest.java
- src/test/java/com/exasol/releasedroid/usecases/release/ReleaseInteractorTest.java
> Removed validation from ReleaseInteractor for use case "release"

- dependencies.md
- doc/changes/changes_1.5.2.md
- pom.xml
- src/main/resources/release-guide-template.html
> Updated dependencies
